@echo off
SET ONEC_PASSWORD=onec
SET ONEC_USERNAME=onec
SET ONEC_VERSION=8.3.25.1445
SET EDT_VERSION=2021.2.7
SET COVERAGE41C_VERSION=''

SET DOCKER_REGISTRY_URL=localhost:5000
SET DOCKER_LOGIN=login
SET DOCKER_PASSWORD=password

SET EXECUTOR_VERSION=3.0.2.2
SET DEV1C_EXECUTOR_API_KEY=YOUR_API_KEY_HERE

SET DOCKER_SYSTEM_PRUNE=false
SET NO_CACHE=false
